// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK2MuTUT5xM-jaPMiMJU41MX3Iuc21Nnc',
    appId: '1:146388083065:web:83912f1f07ce675b450fa8',
    messagingSenderId: '146388083065',
    projectId: 'shopeasee-backend',
    authDomain: 'shopeasee-backend.firebaseapp.com',
    storageBucket: 'shopeasee-backend.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAos9UMYYi2FZkqXHDvC_V4QlhC2-Inpec',
    appId: '1:146388083065:android:82c5b70a10f1772a450fa8',
    messagingSenderId: '146388083065',
    projectId: 'shopeasee-backend',
    storageBucket: 'shopeasee-backend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa3Pr8x1ba2F2tNg8KF04xR1Cg-PYECGk',
    appId: '1:146388083065:ios:004bd64e3243ef64450fa8',
    messagingSenderId: '146388083065',
    projectId: 'shopeasee-backend',
    storageBucket: 'shopeasee-backend.firebasestorage.app',
    iosBundleId: 'com.example.shopEasee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa3Pr8x1ba2F2tNg8KF04xR1Cg-PYECGk',
    appId: '1:146388083065:ios:004bd64e3243ef64450fa8',
    messagingSenderId: '146388083065',
    projectId: 'shopeasee-backend',
    storageBucket: 'shopeasee-backend.firebasestorage.app',
    iosBundleId: 'com.example.shopEasee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCK2MuTUT5xM-jaPMiMJU41MX3Iuc21Nnc',
    appId: '1:146388083065:web:8e9da54e5423665e450fa8',
    messagingSenderId: '146388083065',
    projectId: 'shopeasee-backend',
    authDomain: 'shopeasee-backend.firebaseapp.com',
    storageBucket: 'shopeasee-backend.firebasestorage.app',
  );
}
